mv agenda.c agenda.cpp
mv analysis.c analysis.cpp
mv argacces.c argacces.cpp
mv bload.c bload.cpp
mv bmathfun.c bmathfun.cpp
mv bsave.c bsave.cpp
mv classcom.c classcom.cpp
mv classexm.c classexm.cpp
mv classfun.c classfun.cpp
mv classinf.c classinf.cpp
mv classini.c classini.cpp
mv classpsr.c classpsr.cpp
mv clsltpsr.c clsltpsr.cpp
mv commline.c commline.cpp
mv conscomp.c conscomp.cpp
mv constrct.c constrct.cpp
mv constrnt.c constrnt.cpp
mv crstrtgy.c crstrtgy.cpp
mv cstrcbin.c cstrcbin.cpp
mv cstrccom.c cstrccom.cpp
mv cstrcpsr.c cstrcpsr.cpp
mv cstrnbin.c cstrnbin.cpp
mv cstrnchk.c cstrnchk.cpp
mv cstrncmp.c cstrncmp.cpp
mv cstrnops.c cstrnops.cpp
mv cstrnpsr.c cstrnpsr.cpp
mv cstrnutl.c cstrnutl.cpp
mv default.c default.cpp
mv defins.c defins.cpp
mv developr.c developr.cpp
mv dffctbin.c dffctbin.cpp
mv dffctbsc.c dffctbsc.cpp
mv dffctcmp.c dffctcmp.cpp
mv dffctdef.c dffctdef.cpp
mv dffctpsr.c dffctpsr.cpp
mv dffnxbin.c dffnxbin.cpp
mv dffnxcmp.c dffnxcmp.cpp
mv dffnxexe.c dffnxexe.cpp
mv dffnxfun.c dffnxfun.cpp
mv dffnxpsr.c dffnxpsr.cpp
mv dfinsbin.c dfinsbin.cpp
mv dfinscmp.c dfinscmp.cpp
mv drive.c drive.cpp
mv emathfun.c emathfun.cpp
mv engine.c engine.cpp
mv envrnmnt.c envrnmnt.cpp
mv evaluatn.c evaluatn.cpp
mv expressn.c expressn.cpp
mv exprnbin.c exprnbin.cpp
mv exprnops.c exprnops.cpp
mv exprnpsr.c exprnpsr.cpp
mv extnfunc.c extnfunc.cpp
mv factbin.c factbin.cpp
mv factbld.c factbld.cpp
mv factcmp.c factcmp.cpp
mv factcom.c factcom.cpp
mv factfun.c factfun.cpp
mv factgen.c factgen.cpp
mv facthsh.c facthsh.cpp
mv factlhs.c factlhs.cpp
mv factmch.c factmch.cpp
mv factmngr.c factmngr.cpp
mv factprt.c factprt.cpp
mv factqpsr.c factqpsr.cpp
mv factqury.c factqury.cpp
mv factrete.c factrete.cpp
mv factrhs.c factrhs.cpp
mv filecom.c filecom.cpp
mv filertr.c filertr.cpp
mv generate.c generate.cpp
mv genrcbin.c genrcbin.cpp
mv genrccmp.c genrccmp.cpp
mv genrccom.c genrccom.cpp
mv genrcexe.c genrcexe.cpp
mv genrcfun.c genrcfun.cpp
mv genrcpsr.c genrcpsr.cpp
mv globlbin.c globlbin.cpp
mv globlbsc.c globlbsc.cpp
mv globlcmp.c globlcmp.cpp
mv globlcom.c globlcom.cpp
mv globldef.c globldef.cpp
mv globlpsr.c globlpsr.cpp
mv immthpsr.c immthpsr.cpp
mv incrrset.c incrrset.cpp
mv inherpsr.c inherpsr.cpp
mv inscom.c inscom.cpp
mv insfile.c insfile.cpp
mv insfun.c insfun.cpp
mv insmngr.c insmngr.cpp
mv insmoddp.c insmoddp.cpp
mv insmult.c insmult.cpp
mv inspsr.c inspsr.cpp
mv insquery.c insquery.cpp
mv insqypsr.c insqypsr.cpp
mv iofun.c iofun.cpp
mv lgcldpnd.c lgcldpnd.cpp
mv main.c main.cpp
mv memalloc.c memalloc.cpp
mv miscfun.c miscfun.cpp
mv modulbin.c modulbin.cpp
mv modulbsc.c modulbsc.cpp
mv modulcmp.c modulcmp.cpp
mv moduldef.c moduldef.cpp
mv modulpsr.c modulpsr.cpp
mv modulutl.c modulutl.cpp
mv msgcom.c msgcom.cpp
mv msgfun.c msgfun.cpp
mv msgpass.c msgpass.cpp
mv msgpsr.c msgpsr.cpp
mv multifld.c multifld.cpp
mv multifun.c multifun.cpp
mv objbin.c objbin.cpp
mv objcmp.c objcmp.cpp
mv objrtbin.c objrtbin.cpp
mv objrtbld.c objrtbld.cpp
mv objrtcmp.c objrtcmp.cpp
mv objrtfnx.c objrtfnx.cpp
mv objrtgen.c objrtgen.cpp
mv objrtmch.c objrtmch.cpp
mv parsefun.c parsefun.cpp
mv pattern.c pattern.cpp
mv pprint.c pprint.cpp
mv prccode.c prccode.cpp
mv prcdrfun.c prcdrfun.cpp
mv prcdrpsr.c prcdrpsr.cpp
mv prdctfun.c prdctfun.cpp
mv prntutil.c prntutil.cpp
mv proflfun.c proflfun.cpp
mv reorder.c reorder.cpp
mv reteutil.c reteutil.cpp
mv retract.c retract.cpp
mv router.c router.cpp
mv rulebin.c rulebin.cpp
mv rulebld.c rulebld.cpp
mv rulebsc.c rulebsc.cpp
mv rulecmp.c rulecmp.cpp
mv rulecom.c rulecom.cpp
mv rulecstr.c rulecstr.cpp
mv ruledef.c ruledef.cpp
mv ruledlt.c ruledlt.cpp
mv rulelhs.c rulelhs.cpp
mv rulepsr.c rulepsr.cpp
mv scanner.c scanner.cpp
mv sortfun.c sortfun.cpp
mv strngfun.c strngfun.cpp
mv strngrtr.c strngrtr.cpp
mv symblbin.c symblbin.cpp
mv symblcmp.c symblcmp.cpp
mv symbol.c symbol.cpp
mv sysdep.c sysdep.cpp
mv textpro.c textpro.cpp
mv tmpltbin.c tmpltbin.cpp
mv tmpltbsc.c tmpltbsc.cpp
mv tmpltcmp.c tmpltcmp.cpp
mv tmpltdef.c tmpltdef.cpp
mv tmpltfun.c tmpltfun.cpp
mv tmpltlhs.c tmpltlhs.cpp
mv tmpltpsr.c tmpltpsr.cpp
mv tmpltrhs.c tmpltrhs.cpp
mv tmpltutl.c tmpltutl.cpp
mv userdata.c userdata.cpp
mv userfunctions.c userfunctions.cpp
mv utility.c utility.cpp
mv watch.c watch.cpp
