LOCAL_SRC_FILES := \
		agenda.cpp        \
		analysis.cpp      \
		argacces.cpp      \
		bload.cpp     \
		bmathfun.cpp      \
		bsave.cpp     \
		classcom.cpp      \
		classexm.cpp      \
		classfun.cpp      \
		classinf.cpp      \
		classini.cpp      \
		classpsr.cpp      \
		clsltpsr.cpp      \
		commline.cpp      \
		conscomp.cpp      \
		constrct.cpp      \
		constrnt.cpp      \
		crstrtgy.cpp      \
		cstrcbin.cpp      \
		cstrccom.cpp      \
		cstrcpsr.cpp      \
		cstrnbin.cpp      \
		cstrnchk.cpp      \
		cstrncmp.cpp      \
		cstrnops.cpp      \
		cstrnpsr.cpp      \
		cstrnutl.cpp      \
		default.cpp       \
		defins.cpp        \
		developr.cpp      \
		dffctbin.cpp      \
		dffctbsc.cpp      \
		dffctcmp.cpp      \
		dffctdef.cpp      \
		dffctpsr.cpp      \
		dffnxbin.cpp      \
		dffnxcmp.cpp      \
		dffnxexe.cpp      \
		dffnxfun.cpp      \
		dffnxpsr.cpp      \
		dfinsbin.cpp      \
		dfinscmp.cpp      \
		drive.cpp     \
		emathfun.cpp      \
		engine.cpp        \
		envrnmnt.cpp      \
		evaluatn.cpp      \
		expressn.cpp      \
		exprnbin.cpp      \
		exprnops.cpp      \
		exprnpsr.cpp      \
		extnfunc.cpp      \
		factbin.cpp       \
		factbld.cpp       \
		factcmp.cpp       \
		factcom.cpp       \
		factfun.cpp       \
		factgen.cpp       \
		facthsh.cpp       \
		factlhs.cpp       \
		factmch.cpp       \
		factmngr.cpp      \
		factprt.cpp       \
		factqpsr.cpp      \
		factqury.cpp      \
		factrete.cpp      \
		factrhs.cpp       \
		filecom.cpp       \
		filertr.cpp       \
		generate.cpp      \
		genrcbin.cpp      \
		genrccmp.cpp      \
		genrccom.cpp      \
		genrcexe.cpp      \
		genrcfun.cpp      \
		genrcpsr.cpp      \
		globlbin.cpp      \
		globlbsc.cpp      \
		globlcmp.cpp      \
		globlcom.cpp      \
		globldef.cpp      \
		globlpsr.cpp      \
		immthpsr.cpp      \
		incrrset.cpp      \
		inherpsr.cpp      \
		inscom.cpp        \
		insfile.cpp       \
		insfun.cpp        \
		insmngr.cpp       \
		insmoddp.cpp      \
		insmult.cpp       \
		inspsr.cpp        \
		insquery.cpp      \
		insqypsr.cpp      \
		iofun.cpp     \
		lgcldpnd.cpp      \
		memalloc.cpp      \
		miscfun.cpp       \
		modulbin.cpp      \
		modulbsc.cpp      \
		modulcmp.cpp      \
		moduldef.cpp      \
		modulpsr.cpp      \
		modulutl.cpp      \
		msgcom.cpp        \
		msgfun.cpp        \
		msgpass.cpp       \
		msgpsr.cpp        \
		multifld.cpp      \
		multifun.cpp      \
		objbin.cpp        \
		objcmp.cpp        \
		objrtbin.cpp      \
		objrtbld.cpp      \
		objrtcmp.cpp      \
		objrtfnx.cpp      \
		objrtgen.cpp      \
		objrtmch.cpp      \
		parsefun.cpp      \
		pattern.cpp       \
		pprint.cpp        \
		prccode.cpp       \
		prcdrfun.cpp      \
		prcdrpsr.cpp      \
		prdctfun.cpp      \
		prntutil.cpp      \
		proflfun.cpp      \
		reorder.cpp       \
		reteutil.cpp      \
		retract.cpp       \
		router.cpp        \
		rulebin.cpp       \
		rulebld.cpp       \
		rulebsc.cpp       \
		rulecmp.cpp       \
		rulecom.cpp       \
		rulecstr.cpp      \
		ruledef.cpp       \
		ruledlt.cpp       \
		rulelhs.cpp       \
		rulepsr.cpp       \
		scanner.cpp       \
		sortfun.cpp       \
		strngfun.cpp      \
		strngrtr.cpp      \
		symblbin.cpp      \
		symblcmp.cpp      \
		symbol.cpp        \
		sysdep.cpp        \
		textpro.cpp       \
		tmpltbin.cpp      \
		tmpltbsc.cpp      \
		tmpltcmp.cpp      \
		tmpltdef.cpp      \
		tmpltfun.cpp      \
		tmpltlhs.cpp      \
		tmpltpsr.cpp      \
		tmpltrhs.cpp      \
		tmpltutl.cpp      \
		userdata.cpp      \
		userfunctions.cpp     \
		utility.cpp       \
		watch.cpp 
